version: '3.3'
services:
    minecraft-server:
        volumes:
            - '/home/rares/media/minecraft:/data'
        ports:
            - '25565:25565'
            - '25575:25575'
        environment:
            - MEMORY=12G
            - TYPE=FORGE
            - VERSION=1.12.2
            - FORGE_VERSION=14.23.5.2860
            - EULA=TRUE
        container_name: mc
        tty: true
        stdin_open: true
        restart: unless-stopped
        image: itzg/minecraft-server:java8
