version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
    environment:
      TZ: 'Europe/Bucharest'
      WEBPASSWORD: ''
    volumes:
      - '/home/rares/docker-c/Data/pihole/etc-pihole:/etc/pihole'
      - '/home/rares/docker-c/Data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
