version: '3.3'
services:
    searx:
        volumes:
            - '/home/rares/docker-c/Data/searx:/etc/searx'
        ports:
            - '8080:8080'
        environment:
            - 'BASE_URL=http://localhost:8080/'
        image: searx/searx
        restart: unless-stopped
