---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - WEBUI_PORT=82
    volumes:
      - /home/rares/docker-c/Data/qbittorrent:/config
      - /home/rares/media:/downloads
    ports:
      - 82:82
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
